# Stage 1: Build
FROM python:3.12.1-slim AS builder

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

WORKDIR /root

COPY ./pyproject.toml ./poetry.lock ./startup.sh /root

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    python -m pip install --upgrade pip && \
    pip install --upgrade poetry && \
    poetry config virtualenvs.create false && \
    poetry lock --no-update && \
    poetry install --no-root --no-interaction --no-ansi && \
    chmod +x startup.sh

COPY . /root

# Stage 2: Production
FROM python:3.12.1-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

ENV DJANGO_SUPERUSER_USERNAME=admin
ENV DJANGO_SUPERUSER_PASSWORD=admin
ENV DJANGO_SUPERUSER_EMAIL=admin@example.com

WORKDIR /root

RUN apt-get update && \
    apt-get install -y libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /root /root

CMD ["./startup.sh"]