# Generated by Django 5.1 on 2024-08-22 16:58

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name="NginxLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField()),
                ("http_method", models.CharField(max_length=10)),
                ("uri", models.TextField()),
                ("response_code", models.IntegerField()),
                ("response_size", models.BigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"],
                        name="logs_nginxl_ip_addr_850354_idx",
                    ),
                    models.Index(
                        fields=["timestamp"],
                        name="logs_nginxl_timesta_4f3f8a_idx",
                    ),
                    models.Index(
                        fields=["response_code"],
                        name="logs_nginxl_respons_0d8d71_idx",
                    ),
                    GinIndex(
                        fields=["uri"],
                        name="gin_uri_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
    ]
