# Generated by Django 5.1 on 2024-08-23 00:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nginxlog',
            name='gin_uri_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='nginxlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['uri'], name='logs_nginxl_uri_01c31e_gin'),
        ),
    ]
